// AUTH
const AUTH_PREFIX = 'AUTH.';
export const LOGIN = `${AUTH_PREFIX}LOGIN`;
export const LOGIN_SUCCESS = `${AUTH_PREFIX}LOGIN_SUCCESS`;
export const LOGIN_FAIL = `${AUTH_PREFIX}LOGIN_FAIL`;
export const LOG_OUT = `${AUTH_PREFIX}LOG_OUT`;

// PRODUCT
const PRODUCT_PREFIX = 'PRODUCT.';
export const GET_PRODUCTS = `${PRODUCT_PREFIX}GET_PRODUCTS`;
export const GET_PRODUCTS_SUCCESS =`${PRODUCT_PREFIX}GET_PRODUCTS_SUCCESS`;
export const GET_PRODUCTS_FAIL = `${PRODUCT_PREFIX}GET_PRODUCTS_FAILS`;

// CUSTOMER
const CUSTOMER_PREFIX = 'CUSTOMER.';
export const CREATE_CUSTOMER = `${CUSTOMER_PREFIX}CREATE_CUSTOMER`;
export const CREATE_CUSTOMER_SUCCESS = `${CUSTOMER_PREFIX}CREATE_CUSTOMER_SUCCESS`;
export const CREATE_CUSTOMER_FAIL = `${CUSTOMER_PREFIX}CREATE_CUSTOMER_FAIL`;