// AUTH
const AUTH_PREFIX = 'AUTH.';
export const LOGIN = `${AUTH_PREFIX}LOGIN`;
export const LOGIN_SUCCESS = `${AUTH_PREFIX}LOGIN_SUCCESS`;
export const OWNER_LOGIN_SUCCESS = `${AUTH_PREFIX}OWNER_LOGIN_SUCCESS`;
export const LOGIN_FAIL = `${AUTH_PREFIX}LOGIN_FAIL`;
export const LOG_OUT = `${AUTH_PREFIX}LOG_OUT`;

// PRODUCT
const PRODUCT_PREFIX = 'PRODUCT.';
export const GET_PRODUCTS = `${PRODUCT_PREFIX}GET_PRODUCTS`;
export const GET_PRODUCTS_SUCCESS =`${PRODUCT_PREFIX}GET_PRODUCTS_SUCCESS`;
export const GET_PRODUCTS_FAIL = `${PRODUCT_PREFIX}GET_PRODUCTS_FAILS`;

// CUSTOMER
const CUSTOMER_PREFIX = 'CUSTOMER.';
export const CREATE_CUSTOMER = `${CUSTOMER_PREFIX}CREATE_CUSTOMER`;
export const CREATE_CUSTOMER_SUCCESS = `${CUSTOMER_PREFIX}CREATE_CUSTOMER_SUCCESS`;
export const CREATE_CUSTOMER_FAIL = `${CUSTOMER_PREFIX}CREATE_CUSTOMER_FAIL`;
export const CLEAR_SELECTED_CUSTOMER = `${CUSTOMER_PREFIX}CLEAR_SELECTED_CUSTOMER`;
export const CHANGE_SELECTED_CUSTOMER = `${CUSTOMER_PREFIX}CHANGE_SELECTED_CUSTOMER`;
export const UPDATE_CUSTOMER = `${CUSTOMER_PREFIX}UPDATE_CUSTOMER`;
export const UPDATE_CUSTOMER_SUCCESS = `${CUSTOMER_PREFIX}UPDATE_CUSTOMER_SUCCESS`;
export const UPDATE_CUSTOMER_FAIL = `${CUSTOMER_PREFIX}UPDATE_CUSTOMER_FAIL`;

// ORDER
const ORDER_PREFIX = 'ORDER.';
export const CREATE_ORDER = `${ORDER_PREFIX}CREATE_ORDER`;
export const REMOVE_ITEM = `${ORDER_PREFIX}REMOVE_ITEM`;
export const INCREASE_ITEM_QUANTITY = `${ORDER_PREFIX}INCREASE_ITEM_QUANTITY`;
export const DECREASE_ITEM_QUANTITY = `${ORDER_PREFIX}DECREASE_ITEM_QUANTITY`;
export const CHECKOUT = `${ORDER_PREFIX}CHECKOUT`;
export const CHECKOUT_SUCCESS = `${ORDER_PREFIX}CHECKOUT_SUCCESS`;
export const CHECKOUT_FAIL = `${ORDER_PREFIX}CHECKOUT_FAIL`;
export const UPDATE_ORDER_BY_CUSTOMER = `${ORDER_PREFIX}UPDATE_ORDER_BY_CUSTOMER`;

//APP
const APP_PREFIX = 'APP.';
export const TOGGLE_LIST_PRODUCT = `${APP_PREFIX}TOGGLE_LIST_PRODUCT`;

//STAFFS
const STAFFS_PREFIX = 'STAFFS.';
export const LOADING_STAFFS = `${STAFFS_PREFIX}LOADING_STAFFS`;
export const LOAD_STAFFS_SUCCESS = `${STAFFS_PREFIX}LOAD_STAFFS_SUCCESS`;
export const LOAD_STAFFS_FAILED = `${STAFFS_PREFIX}LOAD_STAFFS_FAILED`;

//USER
const USER_PREFIX = 'USER.';
export const LOADING_USER = `${USER_PREFIX}LOADING_USER`;
export const LOAD_USER_SUCCESS = `${USER_PREFIX}LOAD_USER_SUCCESS`;
export const LOAD_USER_FAILED = `${USER_PREFIX}LOAD_USER_FAILED`;